### ISSUE TITLE
evacuation

### ISSUE THREAD

**Issue by tpepper** [ciao-project/ciao#102]
Some level of workload migration is desirable.  At a minimum the cloud administrator may want to take a compute node offline for maintenance.  They could issue an evacuate command, which would result in the scheduler needing to choose a new compute node on which to run each workload on the node to be evacuated.  We have ideas on how to implement this crudely (stop/restart) and more kindly (live migration), but have not yet had time to fully architect and implementation.

**Comment by markdryan** [comment]
Fixed by PR

https://github.com/ciao-project/ciao/pull/1429
