### ISSUE TITLE
singlevm: setup.sh problems if not preceded by cleanup

### ISSUE THREAD

**Issue by tpepper** [ciao-project/ciao#1067]
If I run setup.sh and setup.sh, it looks like the second run notices docker ceph and keystone are already running and carries on ignoring the error.  But new keys have been provisioned and subsequent auth attempts in setup.sh result in messages like the following (hostname sanitized):

```main.go:429] ciao-cli FATAL: Get https://host.domain.com:5000/v3/users//projects: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "host.domain.com")```

**Comment by markdryan** [comment]
@rbradford I wonder whether your PR fixes this one.

**Comment by rbradford** [comment]
#1512 switches singlevm to use ciao-deploy and runs cleanup at the start of setup.sh
