### ISSUE TITLE
ciao-cli: implement configuration update command

### ISSUE THREAD

**Issue by mrkz** [ciao-project/ciao#1096]
A cluster **privileged operator** may need to _reconfigure the ciao cluster_ and should be able to update the configuration data as specified by the configuration's [Architecture Overview](https://github.com/01org/ciao/wiki/Configuration#architecture-overview).

Additionally, **privileged operator** may want to _check current cluster configuration_.

Operator should be able to:
* **show** current cluster configuration
* **update** cluster configuration

The fields that would be able to update are defined as specified in #1050 

Purposed CLI command examples are given below:
```
# # # show
$ ciao-cli configuration show

# # # update
$ ciao-cli configuration update identity_service.url https://newserviceurl:newport
$ ciao-cli configuration update launcher.disk_limit true 
```
This is a sub-task of #929 **configuration: Add cluster configuration update support**

**Comment by rbradford** [comment]
Dynamic configuration change is no longer planned / required.
