### ISSUE TITLE
configuration: Implement storeConfiguration method for file backend

### ISSUE THREAD

**Issue by mrkz** [ciao-project/ciao#1185]
Once the new configuration values were successful approved and the SSNTP server has received the new configuration payload, this needs **to store the new configuration using the preferred configuration backend** defined by the schema in the configuration (e.g:  `scheduler.storage_uri: file:///etc/ciao/configuration.yaml` would use the 'file' backend).

For this issue to be resolved this needs to be addressed:
* Implement the [storeConfiguration](https://github.com/01org/ciao/blob/19445f4f42536a6065cc132ad4b13414e5b45452/configuration/driver.go#L36) for the existing backend drivers which are missing at this point ([file backend](https://github.com/01org/ciao/blob/19445f4f42536a6065cc132ad4b13414e5b45452/configuration/file.go#L63))
* Create exported functions to be used by the SSNTP server (in order to use the storeConfiguration function) to save new configuration changes.
* maintain the code coverage level in the current configuration package

This is a sub-task of #929 **configuration: Add cluster configuration update support**

**Comment by rbradford** [comment]
Dynamic configuration change is no longer planned / required.
