### ISSUE TITLE
Documentation for k8s cluster creation

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#1278]
Make a user guide for creating kubernetes clusters with ciao. Post it to the ciao wiki, and include in a README in the code.

**Comment by kaccardi** [comment]
create a blog post about how to set this up with ciao down.

**Comment by kaccardi** [comment]
Add documentation for known issues: persistent storage and k8s external IPs.

**Comment by markdryan** [comment]
I think we can close this one.

It's covered by

https://ciao-project.github.io/kubicle.html
