### ISSUE TITLE
Remove live detatching of volumes from VM instances?

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#1315]
ciao currently supports live attaching and detaching of volumes.  This issue questions whether we should keep the live detaching of volumes feature.  The reasons to remove it being:

1. It only really works well on Fedora.  Support on Ubuntu 16.04 is flaky.  Live detaching sometimes fails and needs to be retried.  This flakyiness can lead to BAT test failures as this feature is tested by BAT.  Live detach doesn't work at all on Clearlinux.
2. The QMP command we use to implement this feature is experimental.
3. We don't have any real use case for this feature right now.
4. It could lead to data loss if the VM is writing to the volume when it is detached by controller.
5. The feature adds complexity to launcher and BAT which is currently hard to justify.

We could remove live detach but keep live attach and detach from stopped volumes.

**Comment by markdryan** [comment]
@kaccardi What do you think about this?

**Comment by kaccardi** [comment]
ok, let's get rid of it. If someone needs this we can reimplement it.

**Comment by rbradford** [comment]
@markdryan wants to address this himself as there is some cleanup that could be in in this part of the code.

**Comment by rbradford** [comment]
@markdryan do you think we should support detach on exited state (i'm thinking not as it's just going to create complexity..)
