### ISSUE TITLE
ciao-down: Parse real sizes (512M, 2G, ...) instead of just a number of GiB

### ISSUE THREAD

**Issue by dlespiau** [ciao-project/ciao#1363]
At the moment we can only specify the VM memory size as an int, the number of GiB to allocate. That's not ideal, the user should be able to specify any size.

**Comment by markdryan** [comment]
This will be important when we add support for multiple VMs.

**Comment by markdryan** [comment]
Moved to https://github.com/intel/ccloudvm/issues/10.
