### ISSUE TITLE
ciao-down: Support inheritance between workloads

### ISSUE THREAD

**Issue by dlespiau** [ciao-project/ciao#1370]
Currently, a lot of boiler plate code has to be copy/pasted (and then maintained) in every workload.

The workload definition should support a `inherit` keyword to inherit from a base workload (and this can be recursive).

ciao-down needs then to merge the parent workload description with the child workload description, including the the cloud-init file.

**Comment by markdryan** [comment]
Moved to https://github.com/intel/ccloudvm/issues/12.
