### ISSUE TITLE
ciao-down: Support different YAML documents separated by '---'

### ISSUE THREAD

**Issue by dlespiau** [ciao-project/ciao#1378]
We currently use the "full" form of YAM documents starting with `---` and ending with `...`. This is really useful only when having non YAML content between two YAML documents. We should also support separating two YAML documents by a simple `---` (without the need to mark the end of a document)

**Comment by markdryan** [comment]
This is already supported. All that's missing is a test case to verify it actually works.

**Comment by markdryan** [comment]
Moved to https://github.com/intel/ccloudvm/issues/17
