### ISSUE TITLE
return node ID during launch failure

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#1475]
If a workload fails to launch due to a launcher failure, return the node ID along with the existing information.

**Comment by kaccardi** [comment]
@markdryan this would make my life so much easier right now. I started trying to do this myself, and realized it would probably be something really fast for you to do, and I'm having a hard time figuring out where you store node id. Probably all the launcher failures could do to have the nodeid tacked onto them.

**Comment by markdryan** [comment]
Yep, I'll do this right now.  I'm trying to work out whether its worth including the node-id when there are other failures.  Strictly, speaking it isn't necessary as you've got the instance id and so you could   use this to find out the node-id.  Having said that, you won't be able to do this if the instance has already been deleted, or stopped, so maybe it's best to include it in all node generated errors.
