### ISSUE TITLE
VM Workloads defintions are ciao instance specific

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#1481]
VM workloads need to specify a backing image in the image service to create their RootFSs.  However, the creator of any given workload cannot know in advance what the uuid of his chosen image is going to be.  This means that he needs to first setup his cluster, upload his backing image, and then create his workload definition.  It also means that his workload definition is not going to work the next time he tears down and sets up his cluster.

We could use fix image ids for but we don't currently do this in SingleVM or I believe ciao-deploy.  What this means is that we cannot currently create a workload for a VM that will work on any of our default cluster setups without modification.  When we start building apps comprised of multiple workload definitions, this modification will be very painful and off putting for potential ciao users.  Imagine the instructions we'd have to provide.

1. Set up your cluster.
2. FInd out the uuid of the ubuntu image.
3. Update these 10 files.
4. Create the workload definitions.

Ideally, they should have to invoke a single command to deploy and teardown their app, but that's another issue.

**Comment by rbradford** [comment]
Named images would fix this. So rather than referring to the uuid you could use name. I think it's probably a good idea to still require the named image to be uploaded before the workload is created on the server.

**Comment by markdryan** [comment]
Fixed by #1595
