### ISSUE TITLE
ciao-controller deletes public workloads when removing tenant

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#1495]
when deleting a tenant, all the public workloads are deleted as well.

**Comment by rbradford** [comment]
I can't reproduce this:

```
rob@singlevm:~/go/src/github.com/ciao-project/ciao/testutil/singlevm$ CIAO_CLIENT_CERT_FILE=$CIAO_ADMIN_CLIENT_CERT_FILE ciao-cli tenant list -all
Tenant [1]
	UUID: 45c97281-821c-472d-91b6-429ad9091a2b
	Name: 
rob@singlevm:~/go/src/github.com/ciao-project/ciao/testutil/singlevm$ ciao-cli workload list
Workload 1
	Name: Ubuntu latest test container
	UUID:c34d0513-e1cf-41ea-8565-362c6e649d14
	CPUs: 2
	Memory: 128 MB
Workload 2
	Name: Debian latest test container
	UUID:df1ec7c6-7065-4c33-b5db-6d378c398b2c
	CPUs: 2
	Memory: 128 MB
Workload 3
	Name: Ubuntu test VM
	UUID:6ab7e3b6-b74d-4893-af49-22bc719b8f31
	CPUs: 2
	Memory: 256 MB
rob@singlevm:~/go/src/github.com/ciao-project/ciao/testutil/singlevm$ CIAO_CLIENT_CERT_FILE=$CIAO_ADMIN_CLIENT_CERT_FILE ciao-cli tenant delete -tenant 45c97281-821c-472d-91b6-429ad9091a2b
rob@singlevm:~/go/src/github.com/ciao-project/ciao/testutil/singlevm$ ciao-cli workload list
Workload 1
	Name: Ubuntu latest test container
	UUID:c34d0513-e1cf-41ea-8565-362c6e649d14
	CPUs: 2
	Memory: 128 MB
Workload 2
	Name: Debian latest test container
	UUID:df1ec7c6-7065-4c33-b5db-6d378c398b2c
	CPUs: 2
	Memory: 128 MB
Workload 3
	Name: Ubuntu test VM
	UUID:6ab7e3b6-b74d-4893-af49-22bc719b8f31
	CPUs: 2
	Memory: 256 MB
```

**Comment by kaccardi** [comment]
Here's how I reproduce it - I'm not sure why it doesn't reproduce for you.
kcaccard@otc-dcs-clr001 ~ $ CIAO_CLIENT_CERT_FILE=$CIAO_ADMIN_CLIENT_CERT_FILE ciao-cli tenant list -all
Tenant [1]
	UUID: 1df5ce09-19cd-42ad-a0e9-fe2cc0ba3f3d
	Name: Demo
kcaccard@otc-dcs-clr001 ~ $ ciao-cli workload list
Workload 1
	Name: Ubuntu latest test container
	UUID:8246e073-ca57-4245-adb2-560a37d246d4
	CPUs: 2
	Memory: 128 MB
Workload 2
	Name: Debian latest test container
	UUID:9b258b59-6b40-4cc1-9c7a-b9e5f9201fdb
	CPUs: 2
	Memory: 128 MB
Workload 3
	Name: Ubuntu test VM
	UUID:a5210522-21d5-4e40-8d35-18aaafeb280e
	CPUs: 2
	Memory: 256 MB
kcaccard@otc-dcs-clr001 ~ $ CIAO_CLIENT_CERT_FILE=$CIAO_ADMIN_CLIENT_CERT_FILE ciao-cli tenant delete -tenant 1df5ce09-19cd-42ad-a0e9-fe2cc0ba3f3d
kcaccard@otc-dcs-clr001 ~ $ ciao-cli workload listkcaccard@otc-dcs-clr001 ~ $

**Comment by kaccardi** [comment]
This was on a physical cluster. I can't imagine that would make a difference.

**Comment by rbradford** [comment]
This was caused by confusion about whether the workloads were public or not. Now with ciao-deploy create-bat-workloads they are tenant private. singlevm now uses this after #1512
