### ISSUE TITLE
when creating tenants programatically, the tenant isn't immediately available to configure.

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#1496]
To reproduce, write a script that does the following:
ciao-deploy auth create demo 1df5ce09-19cd-42ad-a0e9-fe2cc0ba3f3d

CIAO_CLIENT_CERT_FILE=$CIAO_ADMIN_CLIENT_CERT_FILE ciao-cli tenant update -for-tenant 1df5ce09-19cd-42ad-a0e9-fe2cc0ba3f3d -name "Demo" -subnet-bits 17

F1002 10:06:47.568173   67368 main.go:475] ciao-cli FATAL: No tenant by that ID found

**Comment by kaccardi** [comment]
this could be operator error - or we need to change update to create if it doesn't exist.

**Comment by rbradford** [comment]
So you're missing a tenant creation step here. Creating the cert doesn't create the tenant. Maybe it should? When that was written we didn't have tenant creation..

**Comment by kaccardi** [comment]
for some reason it works fine when it's not scripted. I need to figure out why exactly.

**Comment by rbradford** [comment]
If you connect to the cluster with the cert it will get automatically created but only then. Maybe we should remove that feature as it might lead to tenants be inadvertently being recreated after deletion.

**Comment by kaccardi** [comment]
I think this was the problem. so operator error. I think the behavior of update is correct.

**Comment by kaccardi** [comment]
btw - in a production environment the operator should revoke the cert prior to removing the tenant, this would prevent accidentally re-adding the tenant.
