### ISSUE TITLE
ciao-deploy disables memory/disk checking by default

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#1539]
ciao-deploy setup will create a configuration file with disk and memory limits disabled. This is probably not what you would want outside of a developer environment. The default should be geared towards production clusters anyway, and in this case memory/disk limit checking should be enabled so that compute nodes don't run out of memory or disk space.

**Comment by markdryan** [comment]
Let's only enable limits for memory for now.  The concept of disk limits is currently broken, see #1541.
