### ISSUE TITLE
Unable to ping private IP address of instance in a different subnet

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#1620]
Maybe I'm doing something wrong here, but I created two instances in different subnets.  One was assigned IP address 172.16.0.2 and  the other 172.16.0.6.  I then logged into the machine with the IP address of  172.16.0.2 and tried to ping  172.16.0.6.  The ping command hung.  I also tried pinging 172.16.0.6 from 172.16.0.2 and this also failed.  Needless to say both instances were part of the same tenant.  Is this expected?  If so, I think we've got a bit of a problem as users have no control over which subnets are used as a source of their instances' IP addresses.  How can the user be certain that two instances in the same tenant will be able to communicate.

**Comment by markdryan** [comment]
@mcastelino , @kaccardi , should this work?  Am I doing something wrong?

**Comment by markdryan** [comment]
Or is this something that will be addressed by #1608 ?

**Comment by kaccardi** [comment]
right - it wont work right now because currently while we do launch a cnci per subnet, the cnci's can't communicate. Once PR #1608 is complete, this should work.

**Comment by markdryan** [comment]
I confirm that this is fixed by #1608
