### ISSUE TITLE
container networking may not work when subnet mask is not == 24

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#1626]
I haven't actually tested this to see whether this is the case but looking at the code of the networking plugin I see this.

https://github.com/ciao-project/ciao/blob/master/networking/libsnnet/docker_plugin.go#L706

This means that the IPAM plugin is returning the wrong address to docker when docker calls RequestAddress

https://github.com/docker/libnetwork/blob/master/docs/ipam.md#requestaddress

**Comment by kaccardi** [comment]
is this a duplicate of #1545

**Comment by markdryan** [comment]
Yes it is.  I'll close.
