### ISSUE TITLE
workload validator

### ISSUE THREAD

**Issue by tpepper** [ciao-project/ciao#244]
As we build a workload creator, we need a workload validator.  We might want it runnable directly from the cli if a workload template can exist locally in file form (eg: export workload to file for sharnig with another cloud?).  For a workload created in the web UI, the user should have a "validate" button available, where by the workload definition that is being created is programmatically passed through the validator.

**Comment by tpepper** [comment]
There was a question of whether this would validate the cloud-init contents.  I don't think so, rather focus on things like does the workload reference non-existent resources, push the tenant over quota or if unlimited quota would it be liable to incur crazy cost (eg: just b/c you've no quota you might have mistyped and put a few extra zeros in a resource demand or something like that).  Basic sanity checking to allow highlighting of possibly non-sane requests.

**Comment by rbradford** [comment]
Workload definitions are validated in controller and in the CLI.
