### ISSUE TITLE
Add Pause and Resume

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#276]
SSNTP supports PAUSE and RESUME commands but they are not implemented by other parts of CIAO.  We also haven't really defined what the semantics of pause and resume are with respect to the various workload types we support, currently qemu and docker.  This task is then to:
1. Verify that we actually want to implement PAUSE and RESUME.
2. Identify the semantics of PAUSE and RESUME in a CIAO cluster for all workload types.
3. Make the necessary changes to ciao-launcher, ciao-controller and ciao-cli.

**Comment by rbradford** [comment]
I feel we don't want to do this now that we have stop/restart.
