### ISSUE TITLE
ciao-cli: Request to create two instances sometimes results in the creation of a single instance

### ISSUE THREAD

**Issue by mcastelino** [ciao-project/ciao#61]
Steps to duplicate:
The following two command multiple times
ciao-cli -launch-instances -instances 2 -workload ab68111c-03a6-11e6-87de-001320fb6e31
ciao-cli -list-instances

Detailed logs at http://pastebin.intel.com/view/f68201b6

Not sure if it is a cli issue, but the cli exposes this failure.

**Comment by rbradford** [comment]
Closing this issue as the pastebin containing the logs has expired and the code for launching instances has changed substantially since this issue was opened.
