### ISSUE TITLE
controller api: support for os-volume_attachments 

### ISSUE THREAD

**Issue by jorgevgut** [ciao-project/ciao#627]
Hi, would it be possible to support endpoint compatible with POST /v2.1/{tenant}/servers/{serverid}/os-volume_attachments ?

This is the endpoint web-ui is currently using to attach volumes.

**Comment by tpepper** [comment]
We have implemented the Cinder API, and have not the Nova API.  Nova has a bunch of duplicated calls for image/volume management.  They may be being deprecated so tools preferentially use the cinder and glance APIs directly, not the duplicated functionality.  Typical Openstack tools do use the Nova calls for volume attachment today.

Tools could be changed, the API implemented, or the API mapped inside Ciao to the existing cinder api endpoint implementation.
