### ISSUE TITLE
run ciao as non root

### ISSUE THREAD

**Issue by tpepper** [ciao-project/ciao#669]
Our unit tests, single VM tests, and production today are simply using the root user as a lazy crutch.

From a security perspective, it would be better if most of Ciao did not run as root in our preferred deployments (eg: as noted in documentation, as implemented in ansible, as implemented in single-VM, as implemented in travis CI).

From a developer perspective, it is reasonable to think you can "go get github.com/01org/ciao" and "go test -v ./...", but today that does not work.  One reason is that our unit tests are partly function/system test and need some cluster config on the test machine (see issue #648), but the other is that some of the tests require root, especially in networking.

A useful cleanup exercise would be to start with creating a ciao user/group, give that group permission for /dev/kvm.  Then try to run a cluster with components launched as the ciao user instead of root.  And try running go test as a user in the ciao group.  Catalog what doesn't work.

Networking and network tests we already know have some complexities around requiring root.  @mcastelino thinks we might be able to do something with namespaces....a ciao namespace...in which we run tests.

**Comment by mrkz** [comment]
removing the 'configuration' label as this task looks non-related to the [configuration component](https://github.com/01org/ciao/wiki/Configuration)

**Comment by tpepper** [comment]
@mrkz my thinking was that depending on the implementation it might be a configuration input to deployment automation to specify the user under which ciao components should run.

**Comment by mrkz** [comment]
@tpepper some services (such as [ciao-scheduler](https://github.com/01org/ciao/blob/master/_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/ciao-scheduler.service.j2#L10)) already are run as the `ciao` user (which is already exists in clearlinux OS and is [created in the packages](https://build.opensuse.org/package/view_file/home:clearlinux:preview:ciao/ciao/ciao.spec?expand=1)).

Other services required to be run as root due to the nature of the service (such as the ciao-launcher which requires privileges to create VMs).

So this is addressed by using the ciao deployment method if I'm not mistaken, can you please confirm @albertomurillo ?

**Comment by markdryan** [comment]
> Other services required to be run as root due to the nature of the service (such as the ciao-launcher which requires privileges to create VMs).

Launcher needs to run as root as the moment for two reasons:

1. osprepare
2. creating gre tunnels

It doesn't need to run as root to be able to launch vms.  And to be honest we shouldn't be launching VMs as root.  The qemu documentation discourages this.

If we removed OS prepare from launcher it would be possible to run launcher as root but get it to drop the privileges it doesn't need and for it to run qemu as non-root.

@tpepper I entered a similar ticket (#917) for singlevm a while back.  Perhaps we could close #917 as a duplicate of this issue.

**Comment by mcastelino** [comment]
@markdryan I like the approach where we no longer launch QEMU as root. But the rest of launcher probably need to stay as root.

**Comment by markdryan** [comment]
@mcastelino I guess there will be issues with docker as well, unless the launcher user is part of the docker group.  In any case, not running qemu instances as root will be a good start.

**Comment by tpepper** [comment]
@mrkz yes.  Yesterday I switch it to ciao-deployment.

I agree with @markdryan and am closing #917 as a duplicate of this one.

**Comment by albertomurillo** [comment]
# Services running as root
- ~~ciao-scheduler~~
- ciao-controller
- ciao-launcher

**Comment by albertomurillo** [comment]
PR https://github.com/01org/ciao/pull/1198 allows ciao-controller to be run as `ciao`

**Comment by markdryan** [comment]
The current plan is:

1. Add a new option to all ciao-binaries that install components via osprepare.  Osprepare will no longer get called in the normal ciao start up path.
2. Create a new set of systemd unit files that run the ciao components as root specifying the --install flag.
3. Modify ciao-deploy to create a ciao group and user on each node and add this user to the docker group.
4. Modify the existing systemd unit files to depend on the new installation unit files, and to launch ciao services as the ciao user.  Launcher will need to be granted some additional permissions.
5. Make ciao-launcher hard-reset delete the instances directory.

**Comment by tpepper** [comment]
I like it!
