### ISSUE TITLE
Single VM: Fix controller and image server races

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#686]
The SingleVM setup script launchers controller and the image service in the background.  It then proceeds to issue ciao-cli commands.  The problem is that if these two services are not up and running and have not started to listen on their respective sockets before the first ciao-cli command is issued, the ciao-cli command will fail.  The get around this problem there are a number of sleep statements build into the setup.sh.  However, there's no guarantee that the periods of sleep in the scripts will always be adequate.  We need to find a better solution, e.g.,
1. Fork controller and image service when they've finished their setup, exiting the parent.  The setup.sh script would block until the parent quits.  This is what qemu does in daemonize mode.
2. Use systemd to open the tcp socket for us.

**Comment by rbradford** [comment]
Image server is now part of controller so this race does not happen..
