### ISSUE TITLE
gophercloud: unbounded recursion on auth failure in ProviderClient.Request()

### ISSUE THREAD

**Issue by bwarden** [ciao-project/ciao#802]
If AllowReauth is enabled when creating a service client, authentication failures will trigger a recursive path. If authentication fails, the Request method will call ReauthFunc, then call itself recursively. This handles 401->201 transitions, but becomes unbounded if the response is never successful, e.g. incorrect credentials.

A potential solution is to remove the client's ReauthFunc when recursing, so that the second invocation of Request will not recurse further. It remains to be determined whether this is safe, however.

**Comment by kaccardi** [comment]
@bwarden please check github.com/gophercloud to see if the issue exists and file there if it does.

**Comment by bwarden** [comment]
https://github.com/gophercloud/gophercloud/issues/187

**Comment by bwarden** [comment]
Upstream bug rejected, referring to https://github.com/gophercloud/gophercloud/blob/master/auth_options.go#L46, which suggests we should add a custom HTTP agent to our implementation, e.g. https://github.com/rackspace/rack/blob/1.0.0/auth/clients.go#L311

**Comment by markdryan** [comment]
@rbradford Do we even use this code any more?

**Comment by rbradford** [comment]
We don't use this code anymore.
