### ISSUE TITLE
ssntp: uuid: Parse doesn't work for all uuid4 strings

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#976]
ssntp/uuid.Parse assumes that you have a uuid4 string with '-' as separators. the '-' should be optional.

**Comment by markdryan** [comment]
uuid.Parse parses rfc4122 UUIDs.  As far as I can tell, the '-'s are mandatory in the string representation of all rfc4122 UUIDs, so Parse is correctly implemented.

What is the use case that requires us to parse UUIDs without the '-'s?

**Comment by kaccardi** [comment]
@markdryan The UUIDs for the tenants that keystone generates do not contain '-'. For input validation it'd be nice to use Parse to prove a UUID string is valid, but it doesn't work for tenant IDs.

**Comment by markdryan** [comment]
I guess the best thing to do would be to provide a new function that accepts the '-'less format.

**Comment by rbradford** [comment]
Our tenant UUIDs now have dashes so we can close this.
